global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

# Rule files to load
rule_files:
  - 'alert.rules.yml'

# Scrape configurations
scrape_configs:
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitor the DOS application
  - job_name: 'dos'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    
  # Monitor Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']
    metrics_path: '/metrics'
    
  # Monitor Node Exporter (for host metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

# Alerting rules
rule_files:
  - 'alert.rules.yml'
